name: Docker Image CI
on: [push]
env:
  OPENSSH_VERSION: openssh-8.2p1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg OPENSSH_VERSION=$OPENSSH_VERSION --tag bitnp/gitlab-ce:nightly
    - name: Start the container
      run: |
        docker run -d --name test bitnp/gitlab-ce:nightly
        sleep 10
    - name: Test SSH version
      run: |
        if docker ps -a | grep test | grep "Stop\|Restart\|Exit"; then docker logs test;exit 1; fi
        export TEST_DOCKER_IP=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' test`
        docker exec -it test ssh -v git@127.0.0.1 2>&1
        if ! docker exec -it test ssh -v git@127.0.0.1 2>&1 | grep "${OPENSSH_VERSION/-/_}"; then docker ps && docker logs test;exit 1; fi
